# Generated by Django 4.1 on 2025-02-06 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockVisualizer', '0002_alter_stockdata_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.TextField(null=True)),
                ('data', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
